#!/bin/bash
for d in [0-9][0-9][0-9][0-9]
do 
	( cd $d && strings *.file > strings && file *.file > file1 && md5sum *.file > md5 && sha256sum *.file >> md5 && strings -el *.file > stringsEL && rabin2 -e *.file >> file1 && rabin2 -AC *.file >> file1 && printf "\n" >> file1 && rabin2 -i *.file >> file1 && printf "\n" >> file1 && rabin2 -s *.file >> file1
)
done
